const assert=require('node:assert/strict');
const timeline=require('../js/timeline-engine.js');
const plan={hasPartner:true,people:[{name:'Ryan',birthDate:'1974-07-23',retirementAge:55},{name:'Partner',birthDate:'1980-01-15',retirementAge:55}],household:{planningAge:95},incomeSources:[{name:'CPP',type:'CPP',owner:'Ryan',startAge:70,endAge:110}],events:[{name:'Major purchase',type:'Expense',year:2032,amount:25000}]};
assert.equal(timeline.ageAtYearEnd('1974-07-23',2026),52);
assert.equal(timeline.yearAtAge('1974-07-23',55.5),2030);
const rows=timeline.buildTimeline(plan,{startYear:2026,planningAge:95});
assert.equal(rows[0].year,2026);
assert.equal(rows.at(-1).year,2075);
assert.equal(rows.find(r=>r.year===2029).people[0].status,'Retired');
assert.ok(rows.find(r=>r.year===2044).events.some(e=>e.name==='CPP begins'));
assert.ok(rows.find(r=>r.year===2032).events.some(e=>e.name==='Major purchase'));
const self=timeline.runSelfTests();assert.equal(self.ok,true,self.failed.join(', '));
console.log(`Timeline engine tests passed (${self.total} embedded + 7 Node assertions).`);
